const getters = {
    //user
    token: (state) => state.user.token,
    userId: (state) => state.user.userId,
    userInfo: (state) => state.user.userInfo,
    userOrderList: (state) => state.user.userOrderList,
    orderDetailModalVisible: (state) => state.user.orderDetailModalVisible,
    currentOrder: (state) => state.user.currentOrder,
    hotelListLoading: (state) => state.hotel.hotelListLoading,
    hotelList: (state) => state.hotel.hotelList,
    searchList: (state) => state.hotel.searchList,
    currentHotelInfo: (state) => state.hotel.currentHotelInfo,
    currentHotelId: (state) => state.hotel.currentHotelId,
    orderModalVisible: (state) => state.hotel.orderModalVisible,
    currentOrderRoom: (state) => state.hotel.currentOrderRoom,
    orderMatchCouponList: (state) => state.hotel.orderMatchCouponList,
    getMembershipModalVisible: (state) => state.user.getMembershipModalVisible,
    evaluateModalVisible: (state) => state.hotel.evaluateModalVisible,
    distributedRooms: (state) => state.hotel.distributedRooms,
    datePickVisible: (state) => state.hotel.datePickVisible,
    startDate: (state) => state.hotel.startDate,
    endDate: (state) => state.hotel.endDate,
    //admin
    managerList: (state) => state.admin.managerList,
    clientList: (state) => state.admin.clientList,
    salesmanList: (state) => state.admin.salesmanList,
    addManagerModalVisible: (state) => state.admin.addManagerModalVisible,
    addSalesmanModalVisible: (state) => state.admin.addSalesmanModalVisible,
    modifyInfoModalVisible: (state) => state.admin.modifyInfoModalVisible,
    addManagerParams: (state) => state.admin.addManagerParams,
    modifyingUserId: (state) => state.admin.modifyingUserId,
    modifyingUserInfo: (state) => state.admin.modifyingUserInfo,
    //hotelManager
    orderList: (state) => state.hotelManager.orderList,
    addHotelModalVisible: (state) => state.hotelManager.addHotelModalVisible,
    addRoomModalVisible: (state) => state.hotelManager.addRoomModalVisible,
    addRoomParams: (state) => state.hotelManager.addRoomParams,
    addHotelParams: (state) => state.hotelManager.addHotelParams,
    couponVisible: (state) => state.hotelManager.couponVisible,
    addCouponVisible: (state) => state.hotelManager.addCouponVisible,
    activeHotelId: (state) => state.hotelManager.activeHotelId,
    couponList: (state) => state.hotelManager.couponList,
    type: (state) => state.hotelManager.type,

    // salesman
    userList: (state) => state.salesman.userList,
    rechargeModalVisible: (state) => state.salesman.rechargeModalVisible,
    currentClient: (state) => state.salesman.currentClient,
    websiteCoupon1List: (state) => state.salesman.websiteCoupon1List,
    websiteCoupon2List: (state) => state.salesman.websiteCoupon2List,
    websiteCoupon3List: (state) => state.salesman.websiteCoupon3List,
    websiteCoupon4List: (state) => state.salesman.websiteCoupon4List,
    addCoupon1Visible: (state) => state.salesman.addCoupon1Visible,
    addCoupon2Visible: (state) => state.salesman.addCoupon2Visible,
    addCoupon3Visible: (state) => state.salesman.addCoupon3Visible,
    addCoupon4Visible: (state) => state.salesman.addCoupon4Visible,

    //credit
    creditList: (state) => state.credit.creditList,
}

export default getters
